"""Declarative base and the conventions every model inherits.

A single ``MetaData`` carrying an explicit naming convention is the load-bearing piece
here: without it, Alembic emits autogenerated constraints with backend-default names that
differ between SQLite (tests) and Postgres (prod), so a migration authored against one and
applied to the other can't reliably drop or alter a constraint by name. Pinning the
convention keeps the SQLite test schema and the Postgres production schema byte-comparable
in everything that matters for migrations.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.db.types import Timestamp, utcnow

_NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=_NAMING_CONVENTION)


class TimestampMixin:
    """``created_at`` / ``updated_at`` audited in UTC.

    Both default in Python (not via a DB ``server_default``) so the value is identical on
    SQLite and Postgres and round-trips timezone-aware; ``updated_at`` advances on UPDATE
    via ``onupdate``.
    """

    created_at: Mapped[datetime] = mapped_column(
        Timestamp, default=utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        Timestamp, default=utcnow, onupdate=utcnow, nullable=False
    )
